### ISSUE TITLE
Error message on installing R package

### ISSUE THREAD

**Issue by y9c** [alexaandru/nvim-lspupdate#5]
![image](https://user-images.githubusercontent.com/5415510/108492492-31e0f800-72e0-11eb-8674-759b18aebc2c.png)

**Comment by alexaandru** [comment]
Thank you very much for the bug report. Just checked the docs (https://www.neonscience.org/resources/learning-hub/tutorials/packages-r) and it seems that `install.packages()` should be used for updates as well. Also, if you look at the output, it does say the package is installed. The actual error is from `echom`, from `nvim`, not from `R`, which means:

1) the install worked and 
2) the output from R contains something that confused `echom`.

I should probably do some output escaping, instead of dumping it raw...

**Comment by alexaandru** [comment]
Added proper escaping of commands and command outputs. Tested and R update works as expected now, and this should also improve for all the other commands.

Just for clarity/completeness, the problem was that I was using `echom '...<msg>...'` to display messages back to nvim. Now if `<msg>` itself contained a quote, that would break the quoting that `echom` expected, and thus would lead to all sorts of errors (i.e. "unknown function X" or "unknown variable Y", etc.).

Once again, thank you for your bug report and helping me make this plugin better :) 

Have a great day!

**Comment by y9c** [comment]
Hi @alexaandru, that solve the error now, but the R session message makes the vim buffer in a mess. 
![image](https://user-images.githubusercontent.com/5415510/108517679-ae84ce00-7302-11eb-9780-08eef243bea5.png)

I think you can add the `--slave` argument, which is recommended for running R script in command line.

**Comment by alexaandru** [comment]
I added `--slave` and there is no change. I also added `-q` (quiet) flag and also no change, it was just as messy.

Gonna add it to the TODO to offer some "less messy" option, perhaps log the actual output to a file and only print `OK` or `Failed` in vim (next to each command, of course), based on the exit status.

**Comment by y9c** [comment]
Thank you @alexaandru, that would be nice!

I wonder whether it is possible to add an UI for LspUpdate command, just in the same way as `:PlugUpdate` in vim-plug and `:PackerUpdate` in packer.nvim.

**Comment by alexaandru** [comment]
Nailed it!! `install.packages()` had a `quiet` option! :) 

As for UI, that's not really in my plans. Any spare time I have for this project, I'd rather put it into getting the rest of LSPs working, rather than in a UI.
